server:
  port: 80

spring:
  redis:
    host: redis.dreamtale.com
    port: 6379
  datasource:
    username: dev001
    password: Dev.qwe123
    name: dreamtale_user
    url: jdbc:mysql://mysql.dreamtale.com:3306/dreamtale_user?useSSL=false&useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.cj.jdbc.Driver

mybatis:
  mapper-locations: classpath:mapper/*/*.xml
  type-aliases-package: com.dreamtale.instant.message.api.mapper

pagehelper:
  helper-dialect: mysql
  reasonable: true
  support-methods-arguments: true
  params: count=countSql
