server:
  port: 80
spring:
#  redis:
#    host: 192.168.51.93
#    port: 6379
  datasource:
    username: root
    password: Ys.123456
    url: jdbc:mysql://mysql.dreamtale.com:3306/house?useUnicode=true&characterEncoding=UTF-8&autoReconnect=true
    driver-class-name: com.mysql.jdbc.Driver
